In [0]:
import torch

In [0]:
def activation(x):
  return 1/(1+torch.exp(-x))
 

In [0]:
torch.manual_seed(7)
features=torch.randn(1,5)
weights=torch.randn_like(features)
bias=torch.randn(1,1)


In [4]:
output=torch.mm(features,weights.reshape(5,1))##we have changed the shape of the torch for doing matmul
result=activation(output+bias)
print(result)

tensor([[0.1595]])


In [0]:
##Multilayer Perceptron
torch.manual_seed(7)

features = torch.randn(1,3)

n_input =features.shape[1]   #we will be doing matmul so we want to create weight matrix row size == output_dim
n_hidden=2
n_output=1
w1=torch.randn(n_input,n_hidden)
#w2 is the weight of hidden layer neurons
w2=torch.randn(n_hidden,n_output)

bias1=torch.randn(1,n_hidden)
bias2=torch.randn(1,n_output)


In [8]:
output=torch.mm(features,w1)
result1=activation(output+bias1)
output1=torch.mm(result1,w2)
resultfinal=activation(output1+bias2)
print(resultfinal)


tensor([[0.3171]])


Numpy to Torch and back
Python has a great feature converting between Numpy arrays and Torch tensors.To create a tensor from Numpy array,use torch.from_numpy() .To convert a tensor to a Numpy Array,use the .numpy() method


In [9]:
import numpy as np
a=np.random.rand(4,3)
a

array([[0.02878423, 0.41726181, 0.38580125],
       [0.37251128, 0.44390579, 0.91700297],
       [0.17162671, 0.20010991, 0.12710068],
       [0.94111615, 0.9098365 , 0.30020041]])

In [11]:
b=torch.from_numpy(a)
b

tensor([[0.0288, 0.4173, 0.3858],
        [0.3725, 0.4439, 0.9170],
        [0.1716, 0.2001, 0.1271],
        [0.9411, 0.9098, 0.3002]], dtype=torch.float64)

In [0]:
b.numpy()

The Memory is shared between the Numpy array and Torch Tensor,so if you change the values in-place of one object,the other will change as well

In [0]:
b.mul_(2)
a